REFRESH_DELAY = 20  # Delay for tkinter update cycle. in terms of milliseconds
# --- GENERAL_ATTRIBUTES ---
PADX =5
PADY =5
BUTTON_WIDTH = 15

# --- IMAGE DIMENSIONS --------
IMAGE_HEIGHT = 740
IMAGE_WIDTH =  1432

# --- LABEL_FRAME ATTRIBUTES---
ROBOT_IP_FRAME_TEXT = "Robot Connection"

# ---CANVAS ATTRIBUTES---
CANVAS_BG = 'WHITE'
# CANVAS_HEIGHT = 740
# CANVAS_WIDTH = 1432
CANVAS_HEIGHT = 950
CANVAS_WIDTH = 1950
CANVAS_BD = 0
CANVAS_HIGHLIGHT = 0
CANVAS_RELIEF = "ridge"

#---BUTTON ATTRIBUTES---
ORIGIN_BUTTON_TEXT = "Choose Origin"
SELECT_TARGET_BUTTON_TEXT = "Choose Target"
ALPHA_BUTTON_TEXT = "Calculate ALPHA"
DRAW_NEEDLE_BUTTON_TEXT = "Draw Needle Line"
CONVERT_PIXEL2COORDINATES_TEXT = "Convert px to Coord."

RECONNECT_IMAGE_TEXT = "Connect IGTL"
CONNECT_IGT_BUTTON_ROW = 3
CONNECT_IGT_BUTTON_COLUMN = 0



SUBMIT_OUTPUT_BUTTON_TEXT = "Submit"
POPULATE_BUTTON_TEXT = "Auto Field"

MM_PER_PIXEL_GRADIENT  = 0.0149
MM_PER_PIXEL_Y_INTERCEPT  = 0.0132

#--- ORGANISATION ---
    #Grid Layout
        # -- Image Settings Frame---
CANVAS_ROW = 0
CANVAS_COLUMN = 0

ORIGIN_BUTTON_ROW = 0
ORIGIN_BUTTON_COLUMN = 0

SELECT_TARGET_BUTTON_ROW = 0
SELECT_TARGET_BUTTON_COLUMN =2

ALPHA_BUTTON_ROW = 3
ALPHA_BUTTON_COLUMN = 1

DRAW_NEEDLE_BUTTON_ROW =0
DRAW_NEEDLE_BUTTON_COLUMN = 1

CONVERT_PIXEL2COORDINATES_ROW =0
CONVERT_PIXEL2COORDINATES_COLUMN =4

DEPTH_COMBO_BOX_ROW = 0
DEPTH_COMBO_BOX_COLUMN = 3

IMAGE_TWO_SCREEN_FREEZE_BUTTON_ROW = 3
IMAGE_TWO_SCREEN_FREEZE_BUTTON_COLUMN = 2

IMAGE_FOUR_SCREEN_FREEZE_BUTTON_ROW = 3
IMAGE_FOUR_SCREEN_FREEZE_BUTTON_COLUMN = 3

        #--- Calibrate RCM-----
RCM_IMG01_CALIBRATE_BUTTON_ROW = 4
RCM_IMG01_CALIBRATE_BUTTON_COLUMN = 0

RCM_IMG02_CALIBRATE_BUTTON_ROW = 4
RCM_IMG02_CALIBRATE_BUTTON_COLUMN = 1

RCM_CALIBRATE_BUTTON_ROW =4
RCM_CALIBRATE_BUTTON_COLUMN =2

RCM_OVERWRITE_X_ENTRY_ROW = 5
RCM_OVERWRITE_X_ENTRY_COLUMN = 0

RCM_OVERWRITE_Y_ENTRY_ROW = 5
RCM_OVERWRITE_Y_ENTRY_COLUMN = 1

RCM_OVERWRITE_BUTTON_ROW = 5
RCM_OVERWRITE_BUTTON_COLUMN = 2

SHOW_RCM_CB_ROW = 4
SHOW_RCM_CB_COLUMN = 3

        #---CheckBox Grid-----
SHOW_ORIGIN_CB_ROW  = 2
SHOW_ORIGIN_CB_COLUMN =0

SHOW_NEEDLE_CB_ROW = 2
SHOW_NEEDLE_CB_COLUMN = 1

SHOW_TARGET_CB_ROW = 2
SHOW_TARGET_CB_COLUMN = 2

SHOW_US_COORD_CB_ROW = 2
SHOW_US_COORD_CB_COLUMN = 3

SHOW_PROJECTED_LINE_CB_ROW = 3
SHOW_PROJECTED_LINE_CB_COLUMN = 4

SHOW_STACKED_IMAGES_CB_ROW = 2
SHOW_STACKED_IMAGES_CB_COLUMN =4

SHOW_INTENDED_LINE_CB_ROW = 4
SHOW_INTENDED_LINE_CB_COLUMN = 4

        # -- Robot Output Frame
SUBMIT_OUTPUT_BUTTON_ROW = 3
SUBMIT_OUTPUT_BUTTON_COLUMN = 1

POPULATE_BUTTON_ROW = 3
POPULATE_BUTTON_COLUMN = 3

    #Robot Data Frame
ROBOT_DATA_FRAME_X = IMAGE_WIDTH
ROBOT_DATA_FRAME_Y = 0
ROBOT_DATA_FRAME_WIDTH = (CANVAS_WIDTH-ROBOT_DATA_FRAME_X)
ROBOT_DATA_FRAME_HEIGHT = 300

    #NEEDLE DRIVER FRAME
NEEDLE_DRIVER_FRAME_X = IMAGE_WIDTH
NEEDLE_DRIVER_FRAME_Y = ROBOT_DATA_FRAME_HEIGHT+ROBOT_DATA_FRAME_Y
NEEDLE_DRIVER_FRAME_WIDTH = (CANVAS_WIDTH-NEEDLE_DRIVER_FRAME_X)
NEEDLE_DRIVER_FRAME_HEIGHT = 250



    #ROBOT_TCP_FRAME
ROBOT_TCP_FRAME_X = 0
ROBOT_TCP_FRAME_Y = 50
ROBOT_TCP_FRAME_WIDTH = 525
ROBOT_TCP_FRAME_HEIGHT = 80

    #Coordinates Layout
IMAGE_SETTING_LBL_FRAME_X = 0
IMAGE_SETTING_LBL_FRAME_Y = IMAGE_HEIGHT
IMAGE_SETTING_LBL_FRAME_WIDTH = IMAGE_WIDTH/2
IMAGE_SETTING_LBL_FRAME_HEIGHT = CANVAS_HEIGHT-IMAGE_SETTING_LBL_FRAME_Y

    #Treeview Layout
TREEVIEW_FRAME_X = IMAGE_WIDTH
TREEVIEW_FRAME_Y = NEEDLE_DRIVER_FRAME_Y+NEEDLE_DRIVER_FRAME_HEIGHT
TREEVIEW_WIDTH = (CANVAS_WIDTH-TREEVIEW_FRAME_X) *0.75
TREEVIEW_HEIGHT = CANVAS_HEIGHT-NEEDLE_DRIVER_FRAME_Y-NEEDLE_DRIVER_FRAME_HEIGHT

    #US information
US_INFO_FRAME_X = TREEVIEW_FRAME_X+TREEVIEW_WIDTH
US_INFO_FRAME_Y = NEEDLE_DRIVER_FRAME_Y+NEEDLE_DRIVER_FRAME_HEIGHT
US_INFO_FRAME_WIDTH = (CANVAS_WIDTH-TREEVIEW_FRAME_X)*0.25
US_INFO_FRAME_HEIGHT = CANVAS_HEIGHT-NEEDLE_DRIVER_FRAME_Y-NEEDLE_DRIVER_FRAME_HEIGHT

ROBOT_IP_FRAME_X = 0
ROBOT_IP_FRAME_Y = 10
ROBOT_IP_FRAME_WIDTH = 525
ROBOT_IP_FRAME_HEIGHT = 40




    #Inside NEEDLE DRIVER FRAME
NEEDLE_DRIVER_X_DIR_MOVE_FRAME_X = 10
NEEDLE_DRIVER_X_DIR_MOVE_FRAME_Y = 10
NEEDLE_DRIVER_X_DIR_MOVE_FRAME_WIDTH = 500
NEEDLE_DRIVER_X_DIR_MOVE_FRAME_HEIGHT = 60

NEEDLE_DRIVER_Y_DIR_MOVE_FRAME_X = 10
NEEDLE_DRIVER_Y_DIR_MOVE_FRAME_Y = 70
NEEDLE_DRIVER_Y_DIR_MOVE_FRAME_WIDTH = 500
NEEDLE_DRIVER_Y_DIR_MOVE_FRAME_HEIGHT = 60

NEEDLE_DRIVER_Z_DIR_MOVE_FRAME_X = 10
NEEDLE_DRIVER_Z_DIR_MOVE_FRAME_Y = 140
NEEDLE_DRIVER_Z_DIR_MOVE_FRAME_WIDTH = 500
NEEDLE_DRIVER_Z_DIR_MOVE_FRAME_HEIGHT = 60

    #Combobox for Commands
COMMAND_COMBO_BOX = ["","ND_HOME_X","ND_HOME_Y","ND_HOME_Z","ND_MOVE_X","ND_MOVE_Y","ND_MOVE_Z", "UR_MOVE_Z_UP", "UR_MOVE_RELATIVE", "UR_MOVE_Z_DOWN"]



#Controller Frame
CONTROLLER_FRAME_X = IMAGE_SETTING_LBL_FRAME_X +IMAGE_SETTING_LBL_FRAME_WIDTH
CONTROLLER_FRAME_Y = IMAGE_HEIGHT
CONTROLLER_FRAME_WIDTH = IMAGE_WIDTH/2
CONTROLLER_FRAME_HEIGHT = CANVAS_HEIGHT-IMAGE_SETTING_LBL_FRAME_Y

    #Tkinter Elements


