REFRESH_DELAY = 10  # Delay for tkinter update cycle. in terms of milliseconds
# --- GENERAL_ATTRIBUTES ---
PADX =20
PADY =5
BUTTON_WIDTH = 15

# --- LABEL_FRAME ATTRIBUTES---
ROBOT_IP_FRAME_TEXT = "Robot Connection"

# ---CANVAS ATTRIBUTES---
CANVAS_BG = 'red'
CANVAS_HEIGHT = 740
CANVAS_WIDTH = 1432
# CANVAS_HEIGHT = 950
# CANVAS_WIDTH = 1800
CANVAS_BD = 0
CANVAS_HIGHLIGHT = 0
CANVAS_RELIEF = "ridge"

#---BUTTON ATTRIBUTES---
ORIGIN_BUTTON_TEXT = "Draw Origin"
SELECT_TARGET_BUTTON_TEXT = "Choose Target"
THETA_BUTTON_TEXT = "Calculate Theta"
DRAW_NEEDLE_BUTTON_TEXT = "Draw Needle Line"
CONVERT_PIXEL2COORDINATES_TEXT = "Convert px to Coord."

SUBMIT_OUTPUT_BUTTON_TEXT = "Submit"
POPULATE_BUTTON_TEXT = "Auto Field"



#--- ORGANISATION ---
    #Grid Layout
        # -- Image Settings Frame---
CANVAS_ROW = 0
CANVAS_COLUMN = 0

ORIGIN_BUTTON_ROW = 0
ORIGIN_BUTTON_COLUMN = 0

SELECT_TARGET_BUTTON_ROW = 0
SELECT_TARGET_BUTTON_COLUMN =1

THETA_BUTTON_ROW = 0
THETA_BUTTON_COLUMN = 3

DRAW_NEEDLE_BUTTON_ROW =0
DRAW_NEEDLE_BUTTON_COLUMN =2

CONVERT_PIXEL2COORDINATES_ROW =0
CONVERT_PIXEL2COORDINATES_COLUMN =6

        # -- Robot Output Frame
SUBMIT_OUTPUT_BUTTON_ROW = 3
SUBMIT_OUTPUT_BUTTON_COLUMN = 1

POPULATE_BUTTON_ROW = 3
POPULATE_BUTTON_COLUMN = 3

        #Robot IP Frame



    #Coordinates Layout
IMAGE_SETTING_LBL_FRAME_X = 0
IMAGE_SETTING_LBL_FRAME_Y = 768
IMAGE_SETTING_LBL_FRAME_WIDTH = 1024
IMAGE_SETTING_LBL_FRAME_HEIGHT = 100

ROBOT_IP_FRAME_X = 0
ROBOT_IP_FRAME_Y = 10
ROBOT_IP_FRAME_WIDTH = 525
ROBOT_IP_FRAME_HEIGHT = 40
